apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argus.fullname" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "argus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "argus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "argus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-db-ready
          image: postgres:18.1
          command: ['sh', '-c',
            'until pg_isready -h {{ .Release.Name }}-postgresql -p 5432;
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ARGUS_FRONTEND_URL
              value: {{ .Values.argus.frontendUrl | quote }}
            - name: TIME_ZONE
              value: {{ .Values.argus.timeZone | quote }}
            - name: EMAIL_HOST
              value: {{ .Values.argus.emailHost | quote }}
            - name: EMAIL_PORT
              value: {{ .Values.argus.emailPort | quote }}
            - name: DEFAULT_FROM_EMAIL
              value: {{ .Values.argus.defaultFromEmail | quote }}
            - name: EMAIL_USE_TLS
              value: {{ .Values.argus.emailUseTLS | quote }}
            - name: DEBUG
              value: {{ .Values.argus.debug | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.argus.djangoSettingsModule | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.argus.databaseName | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.argus.databasePort | quote }}
            {{ if .Values.argus.argusExistingSecret }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argus.argusExistingSecret | quote }}
                  key: {{ .Values.argus.secretKeys.djangoSecretKey | quote }}
            - name: ARGUS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argus.argusExistingSecret | quote }}
                  key: {{ .Values.argus.secretKeys.argusUsernameKey | quote }}
            - name: ARGUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argus.argusExistingSecret | quote }}
                  key: {{ .Values.argus.secretKeys.argusPasswordKey | quote }}
            {{ else}}
            - name: SECRET_KEY
              value: {{ .Values.argus.djangoSecret | quote }}
            - name: ARGUS_USERNAME
              value: {{ .Values.argus.argusUsername | quote }}
            - name: ARGUS_PASSWORD
              value: {{ .Values.argus.argusPassword | quote }}
            {{ end }}
            {{ if .Values.argus.databaseExistingSecret }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argus.databaseExistingSecret | quote }}
                  key: {{ .Values.argus.secretKeys.databaseUsernameKey | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argus.databaseExistingSecret | quote }}
                  key: {{ .Values.argus.secretKeys.databasePasswordKey | quote }}
            {{ else }}
            - name: DATABASE_USERNAME
              value: {{ .Values.argus.databaseUsername | quote }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.argus.databasePassword | quote }}
            {{ end }}

            {{ if .Values.postgresql.enabled }}
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-postgresql
            {{ else }}
            - name: DATABASE_HOST
              value: {{ .Values.argus.databaseHost | quote }}
            {{ end }}
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
